---
dataset:
  train: ../data/train
  val: ../data/val
  test: ../data/test
  num_classes: 7


dataloader:
  batch_size: 1
  num_workers: 4

param:
  rpn_sigma: 3.
  roi_sigma: 1.
  weight_decay: 0.0005
  lr_decay: 0.1
  lr: 1e-3

visualization:
  LOG_DIR: runs/faster_rcnn

...
  
